#model_name:
#  hyper_parameter_1: [List of things]
#  hyper_parameter_2: [List of things]
#  hyper_parameter_3: SomeThing

multitask_learner_auto_encoder:
  alpha: [0.001, 0.005, 0.01]
  beta: [0.5, 1, 1.5]
  autencoder_bottle_neck_feature_size: [64, 128, 256]
  autoencoder_num_layers: [1]
  shared_hidden_layer_size: [128, 256, 512]
  user_dense_layer_hidden_size: [32, 64, 128, 256]
  num_classes: 3
  shared_layer_dropout_prob: 0
  user_head_dropout_prob: 0
  learning_rate: [0.00001, 0.00005, 0.0001]
  n_epochs: 400
  decay: [0.0001]
  # Data
  hitogram_seq_len: [24]
  # Loss
  reconstruction_loss_reduction: ['sum']
  use_histogram: True
  ordinal_regression_head: False
  train_only_with_covariates: False
